sudo: false
language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5

before_script:
  - git clone --depth=50 --branch=2017.01 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core && mv ../ai-slim ext/
  - composer require "slim/slim ~3.0"

script:
  - vendor/bin/phing -Ddir=ext/ai-slim coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-slim/.coveralls.yml