sudo: false
language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5

matrix:
  fast_finish: true

before_script:
  - git clone --depth=50 --branch=2018.07 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core && mv ../ai-slim ext/
  - composer require "slim/slim ~3.3"

script:
  - vendor/bin/phing -Ddir=ext/ai-slim coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-slim/.coveralls.yml
